name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - 'with-framework/container/**'

defaults:
  run:
    working-directory: with-framework/container

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build